// Generated by Melange

import * as Main from "./Main.bs.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/./src/legacy/ReactDOMRe.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Main.make, {}), "root");

export {
  
}
/*  Not a pure module */
