// Generated by Melange

import * as React from "react";

console.log("Hello world");

function Main(Props) {
  return React.createElement("div", undefined, "Hello React");
}

var make = Main;

export {
  make ,
  
}
/*  Not a pure module */
