// Generated by Melange

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as List$negCredt from "credt/./library/List.bs.js";
import * as Util$negCredt from "credt/./library/Util.bs.js";

console.log("Hello world");

function reducer(user, email) {
  switch (email.TAG | 0) {
    case /* SetEmail */0 :
        return [
                {
                  id: user.id,
                  name: user.name,
                  email: email._0,
                  age: user.age
                },
                {
                  TAG: /* SetEmail */0,
                  _0: user.email
                }
              ];
    case /* SetName */1 :
        return [
                {
                  id: user.id,
                  name: email._0,
                  email: user.email,
                  age: user.age
                },
                {
                  TAG: /* SetName */1,
                  _0: user.name
                }
              ];
    case /* SetAge */2 :
        return [
                {
                  id: user.id,
                  name: user.name,
                  email: user.email,
                  age: email._0
                },
                {
                  TAG: /* SetAge */2,
                  _0: user.age
                }
              ];
    
  }
}

function getId(u) {
  return u.id;
}

var moduleId = Util$negCredt.idOfString("UserList");

var include = List$negCredt.Make({
      moduleId: moduleId,
      getId: getId,
      reducer: reducer
    });

var addToTransaction = include.addToTransaction;

var UserList_string_of_operation = include.string_of_operation;

var UserList_internalId = include.internalId;

var UserList_wrapper = include.wrapper;

var UserList_getSnapshot = include.getSnapshot;

var UserList_get = include.get;

var UserList_getExn = include.getExn;

var UserList_setData = include.setData;

var UserList_changeListeners = include.changeListeners;

var UserList_addChangeListener = include.addChangeListener;

var UserList_removeChangeListener = include.removeChangeListener;

var UserList_callChangeListeners = include.callChangeListeners;

var UserList_handleOperation = include.handleOperation;

var UserList_baseApply = include.baseApply;

var UserList_applyRemoteOperations = include.applyRemoteOperations;

var UserList_apply = include.apply;

var UserList_length = include.length;

var UserList___resetCollection__ = include.__resetCollection__;

var UserList_instance = include.instance;

var UserList = {
  reducer: reducer,
  string_of_operation: UserList_string_of_operation,
  internalId: UserList_internalId,
  wrapper: UserList_wrapper,
  getSnapshot: UserList_getSnapshot,
  get: UserList_get,
  getExn: UserList_getExn,
  setData: UserList_setData,
  changeListeners: UserList_changeListeners,
  addChangeListener: UserList_addChangeListener,
  removeChangeListener: UserList_removeChangeListener,
  callChangeListeners: UserList_callChangeListeners,
  handleOperation: UserList_handleOperation,
  baseApply: UserList_baseApply,
  applyRemoteOperations: UserList_applyRemoteOperations,
  apply: UserList_apply,
  addToTransaction: addToTransaction,
  length: UserList_length,
  __resetCollection__: UserList___resetCollection__,
  instance: UserList_instance
};

function makeUser(i) {
  return {
          id: Util$negCredt.makeId(undefined),
          name: "Name" + String(i),
          email: "email@" + String(i),
          age: (i << 1)
        };
}

var userStdList = List.init(10, makeUser);

console.log("userStdList", userStdList);

var me_id = Util$negCredt.makeId(undefined);

var me = {
  id: me_id,
  name: "Andreas",
  email: "andreas@eldh.co",
  age: 35
};

console.log("me", me);

var miniMe_id = Util$negCredt.makeId(undefined);

var miniMe = {
  id: miniMe_id,
  name: "Sixten",
  email: "sixten@eldh.co",
  age: 2
};

console.log("miniMe", miniMe);

var __x = Curry._1(addToTransaction, {
      hd: {
        TAG: /* Append */0,
        _0: me
      },
      tl: {
        hd: {
          TAG: /* Update */7,
          _0: me_id,
          _1: {
            TAG: /* SetEmail */0,
            _0: "a@eldh.co"
          }
        },
        tl: {
          hd: {
            TAG: /* Append */0,
            _0: miniMe
          },
          tl: {
            hd: {
              TAG: /* Update */7,
              _0: miniMe_id,
              _1: {
                TAG: /* SetName */1,
                _0: "Sixten Eldh"
              }
            },
            tl: /* [] */0
          }
        }
      }
    });

console.log("userStdList2", __x);

console.log("userStdList2", Belt_List.toArray(userStdList));

function Main(Props) {
  var userStdList$1 = Belt_List.toArray(userStdList);
  return React.createElement("div", undefined, React.createElement("header", undefined, "Hello React"), Belt_Array.mapWithIndex(userStdList$1, (function (i, user) {
                    return React.createElement("li", undefined, React.createElement(React.Fragment, {
                                    children: null,
                                    key: String(i)
                                  }, "name: " + user.name, " ", "email: " + user.email, " ", "age: " + String(user.age)));
                  })));
}

var userStdList2;

var make = Main;

export {
  UserList ,
  makeUser ,
  userStdList ,
  me ,
  miniMe ,
  userStdList2 ,
  make ,
  
}
/*  Not a pure module */
